version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
